from typing import Protocol, Self, TypeAlias, Union, overload

import numpy as np
import numpy.typing as npt
import torch

ArrayLike: TypeAlias = npt.ArrayLike
Array: TypeAlias = np.ndarray | torch.Tensor
Scalar: TypeAlias = Union[int, float]


class Numeric(Protocol):
    def __add__(self, other: Self | Scalar) -> Self: ...
    def __radd__(self, other: Array | Scalar) -> Self: ...

    def __sub__(self, other: Self | Scalar) -> Self: ...
    def __rsub__(self, other: Array | Scalar) -> Self: ...

    @overload
    def __mul__(self, other: Self | Scalar) -> Self: ...
    @overload
    def __mul__(self, other: Array) -> Array: ...
    def __rmul__(self, other: Array | Scalar) -> Self: ...

    def __truediv__(self, other: Self | Scalar) -> Self: ...
    def __rtruediv__(self, other: Array | Scalar) -> Self: ...

    def __pow__(self, other: Self | Scalar) -> Self: ...
    def __rpow__(self, other: Array | Scalar) -> Self: ...

    def __neg__(self) -> Self: ...


Value: TypeAlias = Numeric
